## 端口号  上下文路径
server:
  port: 8080
  servlet:
    context-path: /

## 数据源配置
spring:
  # 数据库配置(务必根据实际情况修改配置)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/mysql?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # 设置连接池为Druid
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源的其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    p6spy:
      # 日志格式
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
      # 自定义日志类
      logging: custom
      custom-appender-class: com.zdslkj.config.StdoutLogger

  # RabbitMQ ??
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /


  ## 启用热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java



#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: is_valid  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值
      logic-not-delete-value: 1 # 逻辑未删除值
